
services:
  web-uwsgi:
    container_name: web-uwsgi
    build: .
    command: uwsgi --ini uwsgi.ini
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment: # Add this section
      - PGPASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    entrypoint: ["/usr/src/app/entrypoint.sh"]

  db:
    container_name: pcfe-db
    image: postgres:latest
    env_file:
      - .env
    restart: always
    user: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      # Determines whether the password is required for authentication
      - POSTGRES_HOST_AUTH_METHOD=${POSTGRES_HOST_AUTH_METHOD}
    volumes:
      - pgdata:/var/lib/postgresql/data/

  nginx:
    image: nginx
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./proxy/proxy.conf:/etc/proxy/proxy.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web-uwsgi

volumes:
  pgdata:
  static_volume:
  media_volume: