
services:
  web-uwsgi:
    container_name: web-uwsgi
    build: .
    command: uwsgi --ini uwsgi.ini
    volumes:
      - .:/usr/src/app
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: pcfe-db
    image: postgres:latest
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTSQL_USER}
      - POSTGRES_PASSWORD=${POSTSQL_PASSWORD}
      - POSTGRES_DB=${POSTSQL_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - web-uwsgi

volumes:
  pgdata:
  static_volume:
  media_volume: