
services:
  web:
    container_name: web-uWSGI
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    container_name: pcfe-db
    image: postgres:latest
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTSQL_USER}
      - POSTGRES_PASSWORD=${POSTSQL_PASSWORD}
      - POSTGRES_DB=${POSTSQL_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  pgdata:
  static_volume:
