# Generated by Django 5.0.4 on 2024-05-30 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EstimatorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(default='default_resume.docs', upload_to=''),
        ),
    ]
